### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by kaiwang12** [ParkinsonLab/Metatranscriptome-Workshop#10]
Hello,
I got a MemoryEerror when running 6_BWA_Gene_Map.py.

I would be appreciated if any help provided. 

Kai

**Comment by billytaj** [comment]
without an error log or anything to go by, i can't help too much.
It's likely your computer doesn't have enough RAM to load your dataset or
one of the libraries.

**Comment by kaiwang12** [comment]
> without an error log or anything to go by, i can't help too much. It's likely your computer doesn't have enough RAM to load your dataset or one of the libraries.
> […](#)

Hi,
Thank you for your quick reply.
My server has 128 Gb RAM. 

Here is the error log information:
Traceback (most recent call last):
  File "./6_BWA_Gene_Map.py", line 117, in <module>
    gene_map(BWA_sam_file, unmapped_reads)
  File "./6_BWA_Gene_Map.py", line 79, in gene_map
    gene2read_map[db_match].append(read)
MemoryError

Kai

**Comment by billytaj** [comment]
did all the other steps work with error?

**Comment by kaiwang12** [comment]
> did all the other steps work with error?
> […](#)

All the other steps work without error. 

Kai

**Comment by billytaj** [comment]
then i have no idea.
memoryerror in python is one of 2 things: either you have no more free
memory on your machine,
or one of the data input files is wrong.

can you absolutely gaurantee no errors whatsoever happened along the way at
every step?
(show all the output logs of every step)

can you guarantee that your server isn't somehow leaking memory or is being
occupied by someone else at runtime?
(ps au)

how big is your dataset? are there funny artifacts in your data?

**Comment by kaiwang12** [comment]
> then i have no idea. memoryerror in python is one of 2 things: either you have no more free memory on your machine, or one of the data input files is wrong. can you absolutely gaurantee no errors whatsoever happened along the way at every step? (show all the output logs of every step) can you guarantee that your server isn't somehow leaking memory or is being occupied by someone else at runtime? (ps au) how big is your dataset? are there funny artifacts in your data?
> […](#)

Actually, I'm using your test dataset (mouse1.fastq). 

1) I can guarantee that I‘m the only user of my server. 

2) Here is the code I used: 
./6_BWA_Gene_Map.py microbial_all_cds.fasta mouse1_contigs_map.tsv mouse1_genes_map.tsv mouse1_genes.fasta mouse1_contigs.fasta mouse1_contigs_annotation_bwa.sam mouse1_contigs_unmapped.fastq mouse1_unassembled.fastq mouse1_unassembled_annotation_bwa.sam mouse1_unassembled_unmapped.fasta

3) I got no errors when I was running the previous steps, but I'll double the output logs. 

Thanks.

**Comment by kaiwang12** [comment]
> then i have no idea. memoryerror in python is one of 2 things: either you have no more free memory on your machine, or one of the data input files is wrong. can you absolutely gaurantee no errors whatsoever happened along the way at every step? (show all the output logs of every step) can you guarantee that your server isn't somehow leaking memory or is being occupied by someone else at runtime? (ps au) how big is your dataset? are there funny artifacts in your data?
> […](#)

Hey,
I modified your code a little bit and it works. 
I just take lines 117-126 out of the for loop. I thought call gene_map function inside the for loop caused MemoryError. 
Please correct me if I'm wrong. 

Thanks. 
Kai

**Comment by kaiwang12** [comment]
> then i have no idea. memoryerror in python is one of 2 things: either you have no more free memory on your machine, or one of the data input files is wrong. can you absolutely gaurantee no errors whatsoever happened along the way at every step? (show all the output logs of every step) can you guarantee that your server isn't somehow leaking memory or is being occupied by someone else at runtime? (ps au) how big is your dataset? are there funny artifacts in your data?
> […](#)

Hey,

Thanks for your reply. 
I think I figured out why I got MemoryError. 

I used Trinity instead of SPAdes to assemble reads. The description line for Trinity contigs has three columns which are separated by space. 

I used the following script to re-format the description line, and then everything works fine. 
awk '{ if (NR%2==1) { print $1 } else { print } }'  mouse1_contigs_trinity.fasta >  mouse1_contigs.fasta

Thanks.

Kai

**Comment by billytaj** [comment]
that would mean you didn't follow the instructions as they were written.

rule of thumb with pipelines: they're extremely inflexible, and are really only meant for the tools they were made for. we can't possibly accomodate for every tool, version, or flavour of every bioinformatic analysis tool out there.
