### ISSUE TITLE
Speeding up the python scripts

### ISSUE THREAD

**Issue by eray-sahin** [ParkinsonLab/Metatranscriptome-Workshop#17]
Hello,

I am trying to use your pipeline for analysis of another metatranscriptomics data, and now the python script#6 is running. The run time of python script #5 was more than 7 days. As I am not familiar with Python language, I wanted to ask a simple question whether it is possible to speed up.

Thank you,

Best regards,

Eray

**Comment by billytaj** [comment]
we don't really recommend using this tutorial to run your own data.  many coding considerations were made specifically for this singular dataset.  we'll be launching a new pipeline, with a new tutorial soon that's much more flexible to people who have their own data to run

**Comment by Felix-Matheri** [comment]
Dear @billytaj whats the progress with this new pipeline? Looking forward https://github.com/ParkinsonLab/Metatranscriptome-Workshop/issues/17#issuecomment-780060979
